---
- name: Add a crontab that runs the tasks daily
  cron: name="run ansible" special_time=daily state=present
        user={{ ansible_ssh_user }}
        job="cd ~/dotfiles; git pull; ansible-playbook -i inventory vagrant.yml"

- name: Update APT cache
  sudo: true
  apt: update_cache=yes

- name: Install libraries using APT
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - ack-grep
    - bash
    - curl
    - git
    - nmap
    - node
    - python
    - python-pip
    - vim
    - wget
    - zsh
    - tmux

- name: Change shell to ZSH
  sudo: true
  user: shell=/bin/zsh name={{ ansible_ssh_user }}
