---
- name: Update APT cache
  become: yes
  apt: update_cache=yes

- name: Install libraries using APT
  become: yes
  apt: name={{ item }} state=latest
  with_items:
    - ack-grep
    - bash
    - curl
    - git
    - nmap
    - python
    - python-pip
    - vim
    - wget
    - zsh
    - tmux
    - mercurial
    - bison

- name: Change shell to ZSH
  become: yes
  user: shell=/bin/zsh name={{ ansible_ssh_user }}
